### ISSUE TITLE
In game werewolf,  when wolves reach an agreement, then start a vote.

### ISSUE THREAD

**Issue by Tallisgo** [modelscope/agentscope#143]
Location: examples/game_werewolf/werewolf.py:

```python
x = sequentialpipeline(wolves)
if x.get("agreement", False):
       break
```
![image](https://github.com/modelscope/agentscope/assets/55240330/9675aef6-1573-4077-b26e-ca142e3b5339)

I just wonder why start vote when wolves don't reach an agreement. but when reach an agreement, wolves need to discuss again?

**Comment by qbc2016** [comment]
`x.get("agreement", False)` means that if `x["agreement"]` is true, then it will jump out of the for loop. `False` is a default value of `x["agreement"]` that prevents the model from returning true correctly due to capacity reasons.

**Comment by DavdGao** [comment]
1. why start vote when wolves don't reach an agreement: 
Maybe the maximum number of discussion rounds is reached (`MAX_WEREWOLF_DISCUSSION_ROUND`). You can try to set a larger number of rounds. 

2. but when reach an agreement, wolves need to discuss again:
In our implementation, once werewolf replies with agreement as `True`, the werewolves will go on voting rather than discussion. Please check the value of the agreement field in line 44 in your figure. 

Maybe LLM replies "True" rather than "true", where "True" cannot be loaded by `json.loads()` as a bool value.

**Comment by DavdGao** [comment]
If you have any further questions or concerns, please feel free to create a new issue. Closing this for now.
